name: pinns
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - ipykernel
  - scipy
